package com.Ecostore.Backend.service;

import com.Ecostore.Backend.dto.AddressDto;
import com.Ecostore.Backend.dto.OrderItemDto;
import com.Ecostore.Backend.model.DiscountCoupon;
import com.Ecostore.Backend.model.Order;
import com.Ecostore.Backend.model.OrderItem;
import com.Ecostore.Backend.model.Product;
import com.Ecostore.Backend.model.User;
import com.Ecostore.Backend.repository.DiscountCouponRepository;
import com.Ecostore.Backend.repository.OrderRepository;
import com.Ecostore.Backend.repository.ProductRepository;
import com.Ecostore.Backend.request.CreateOrderRequest;
import com.Ecostore.Backend.request.PaymentRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class OrderServiceImpl implements OrderService {

    private final OrderRepository orderRepository;
    private final ProductRepository productRepository;
    private final DiscountCouponRepository discountCouponRepository;

    @Autowired
    public OrderServiceImpl(OrderRepository orderRepository, ProductRepository productRepository, DiscountCouponRepository discountCouponRepository) {
        this.orderRepository = orderRepository;
        this.productRepository = productRepository;
        this.discountCouponRepository = discountCouponRepository;
    }

    @Override
    public Order createOrder(User user, CreateOrderRequest req) {
        Order order = new Order();
        order.setUser(user);
        order.setOrderDate(LocalDateTime.now());

        AddressDto shippingAddress = req.getShippingAddress();
        order.setShippingAddress(shippingAddress.getStreetAddress() + ", " + shippingAddress.getCity() + ", " + shippingAddress.getState() + " - " + shippingAddress.getZipCode());

        order.setOrderStatus("PLACED");
        order.setPaymentMethod(req.getPaymentMethod());

        if ("COD".equalsIgnoreCase(req.getPaymentMethod())) {
            order.setPaymentStatus("PENDING");
        } else {
            if (req.getPaymentId() == null || req.getPaymentId().isEmpty()) {
                throw new IllegalArgumentException("Payment ID is required for online payments.");
            }
            order.setPaymentStatus("COMPLETED");
            order.setPaymentId(req.getPaymentId());
        }

        List<OrderItem> preparedOrderItems = new ArrayList<>();
        double totalPrice = 0.0;

        for (OrderItemDto dto : req.getOrderItems()) {
            Product product = productRepository.findById(dto.getProductId())
                    .orElseThrow(() -> new RuntimeException("Product not found with id: " + dto.getProductId()));

            OrderItem orderItem = new OrderItem();
            orderItem.setProduct(product);
            orderItem.setQuantity(dto.getQuantity());
            orderItem.setPrice(product.getPrice() * dto.getQuantity());
            orderItem.setOrder(order);
            preparedOrderItems.add(orderItem);

            totalPrice += orderItem.getPrice();
        }

        order.setOrderItems(preparedOrderItems);
        order.setTotalPrice(totalPrice);

        double finalPrice = totalPrice;
        double discount = 0.0;

        if (req.getCouponCode() != null && !req.getCouponCode().isEmpty()) {
            // First, try to find a matching coupon in the database (percentage-based coupons)
            Optional<DiscountCoupon> couponOpt = discountCouponRepository.findByCode(req.getCouponCode());

            if (couponOpt.isPresent()) {
                DiscountCoupon coupon = couponOpt.get();
                if (!coupon.isActive() || coupon.getExpiryDate().isBefore(LocalDate.now())) {
                    throw new IllegalArgumentException("Coupon is not active or has expired.");
                }
                // Percentage-based discount
                discount = totalPrice * (coupon.getDiscountPercentage() / 100.0);
            } else {
                // Handle fixed-amount coupons generated by the frontend wallet (e.g. ECO50-XXXX, ECO150-XXXX)
                String code = req.getCouponCode().toUpperCase();

                // Wallet coupons require a minimum spend of ₹300 (same rule as frontend)
                if (totalPrice < 300) {
                    throw new IllegalArgumentException("A minimum spend of ₹300 is required to use this coupon.");
                }

                if (code.startsWith("ECO50-")) {
                    discount = Math.min(50, totalPrice);
                } else if (code.startsWith("ECO150-")) {
                    discount = Math.min(150, totalPrice);
                } else {
                    throw new IllegalArgumentException("Invalid coupon code.");
                }
            }
            finalPrice = totalPrice - discount;
        }

        order.setDiscount(discount);
        order.setFinalPrice(finalPrice);

        return orderRepository.save(order);
    }

    @Override
    public List<Order> usersOrderHistory(Long userId) {
        return orderRepository.findByUserId(userId);
    }

    @Override
    public Order findOrderById(Long orderId) throws Exception {
        Optional<Order> opt = orderRepository.findById(orderId);
        if (opt.isPresent()) {
            return opt.get();
        }
        throw new Exception("Order not found with id: " + orderId);
    }

    // ... Implementations for status changes ...
    private Order updateOrderStatus(Long orderId, String status) throws Exception {
        Order order = findOrderById(orderId);
        order.setOrderStatus(status);
        if (status.equals("DELIVERED")) {
            order.setDeliveryDate(LocalDateTime.now());
            order.setPaymentStatus("COMPLETED");
        }
        return orderRepository.save(order);
    }

    @Override
    public Order placedOrder(Long orderId) throws Exception {
        return updateOrderStatus(orderId, "PLACED");
    }

    @Override
    public Order confirmedOrder(Long orderId) throws Exception {
        return updateOrderStatus(orderId, "CONFIRMED");
    }

    @Override
    public Order shippedOrder(Long orderId) throws Exception {
        return updateOrderStatus(orderId, "SHIPPED");
    }

    @Override
    public Order deliveredOrder(Long orderId) throws Exception {
        return updateOrderStatus(orderId, "DELIVERED");
    }

    @Override
    public void deleteOrder(Long orderId) throws Exception {
        Order order = findOrderById(orderId);
        orderRepository.delete(order);
    }

    @Override
    public Order markCodAsPaid(Long orderId) throws Exception {
        Order order = findOrderById(orderId);

        // We should only be able to do this for orders that are actually COD.
        if (!"COD".equalsIgnoreCase(order.getPaymentMethod())) {
            throw new IllegalArgumentException("This order was not placed as Cash on Delivery.");
        }

        // We should only do this for orders where payment is still pending.
        if ("COMPLETED".equalsIgnoreCase(order.getPaymentStatus())) {
            throw new IllegalArgumentException("This order's payment has already been marked as completed.");
        }

        order.setPaymentStatus("COMPLETED");

        return orderRepository.save(order);
    }

    @Override
    public List<Order> getAllOrders() {
        return orderRepository.findAll();
    }

    @Override
    public Order updatePayment(Long orderId, PaymentRequest paymentRequest) throws Exception {
        Order order = findOrderById(orderId);

        order.setPaymentMethod(paymentRequest.getPaymentMethod());
        order.setPaymentId(paymentRequest.getPaymentId());
        order.setPaymentStatus("COMPLETED"); // Once payment details are provided, we mark it as completed.

        return orderRepository.save(order);
    }
}